

#include <QtGlobal>

// Automatically generated by extract_strings_qt.py
#ifdef __GNUC__
#define UNUSED __attribute__((unused))
#else
#define UNUSED
#endif
static const char UNUSED *Flashpaychain_strings[] = {
QT_TRANSLATE_NOOP("Flashpaychain-core", "None"),
QT_TRANSLATE_NOOP("Flashpaychain-core", "None"),
};
